# Generated by Django 5.2.8 on 2026-05-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
