# Generated by Django 5.2.8 on 2026-05-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='department',
            field=models.CharField(blank=True, default='underwriting', max_length=255, null=True),
        ),
    ]
