# Generated by Django 5.2.8 on 2026-02-25 23:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('section', models.CharField(max_length=100)),
                ('action', models.CharField(default='push', max_length=100)),
                ('member_no', models.CharField(blank=True, max_length=50, null=True)),
                ('extra_info', models.JSONField(blank=True, null=True)),
                ('triggered_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
