# Generated by Django 5.2.8 on 2026-03-16 06:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(max_length=100)),
                ('receipt_no', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('allocated_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('levied', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
