# Generated by Django 5.2.8 on 2026-03-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commisions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissionallocation',
            options={'ordering': ['-allocation_date']},
        ),
        migrations.AlterField(
            model_name='commissionallocation',
            name='allocated_amt',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='commissionallocation',
            name='invoice_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commissionallocation',
            name='levied',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='commissionallocation',
            name='receipt_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='commissionallocation',
            index=models.Index(fields=['invoice_no'], name='commission__invoice_f4f5d8_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionallocation',
            index=models.Index(fields=['receipt_no'], name='commission__receipt_baef00_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionallocation',
            index=models.Index(fields=['allocation_date'], name='commission__allocat_4b5ae5_idx'),
        ),
        migrations.AlterModelTable(
            name='commissionallocation',
            table='commission_allocations',
        ),
    ]
