# Generated by Django 5.2.8 on 2026-05-05 14:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commisions', '0002_alter_commissionallocation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('push_note_code', models.IntegerField(blank=True, null=True)),
                ('transaction_number', models.IntegerField(blank=True, null=True)),
                ('debit_no', models.CharField(blank=True, max_length=100, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_code', models.IntegerField(blank=True, null=True)),
                ('customer_code', models.IntegerField(blank=True, null=True)),
                ('intermediary_name', models.CharField(blank=True, max_length=255, null=True)),
                ('broker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('push_note_request_date', models.DateTimeField(blank=True, null=True)),
                ('receipted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('levies', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('available_allocation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('broker_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('withholding_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commission_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transaction_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('primarybenefitname', models.CharField(blank=True, max_length=255, null=True)),
                ('customerspolicycode', models.IntegerField(blank=True, null=True)),
                ('primarybenefitcode', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
