# Generated by Django 5.2.8 on 2026-05-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commisions', '0003_commissionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionrecord',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Fully Paid', 'Fully Paid'), ('Partially Paid', 'Partially Paid'), ('Unpaid', 'Unpaid')], max_length=200, null=True),
        ),
    ]
