# Generated by Django 5.2.8 on 2026-05-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commisions', '0004_commissionrecord_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionrecord',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
