# Generated by Django 5.2.8 on 2026-05-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commisions', '0005_commissionrecord_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commissionrecord',
            old_name='debit_no',
            new_name='debit_code',
        ),
    ]
