# Generated by Django 5.2.8 on 2026-05-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commisions', '0006_rename_debit_no_commissionrecord_debit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionrecord',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissionrecord',
            name='paid_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
