# Generated by Django 5.2.8 on 2026-03-22 13:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopaySyncFailure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corp_id', models.CharField(blank=True, max_length=50, null=True)),
                ('retail_id', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(max_length=100)),
                ('benefit', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('copay_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('request_object', models.JSONField()),
                ('smart_status', models.IntegerField()),
                ('smart_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Copay Sync Failures',
                'db_table': 'copay_sync_failure',
            },
        ),
        migrations.CreateModel(
            name='CopaySyncSuccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corp_id', models.CharField(blank=True, max_length=50, null=True)),
                ('retail_id', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(max_length=100)),
                ('benefit', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('copay_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('request_object', models.JSONField()),
                ('smart_status', models.IntegerField()),
                ('smart_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Copay Sync Successes',
                'db_table': 'copay_sync_success',
            },
        ),
    ]
