# Generated by Django 5.2.8 on 2026-03-28 05:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intergration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberSyncResetLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family_no', models.CharField(max_length=50)),
                ('anniv', models.IntegerField()),
                ('processed', models.BooleanField(default=False)),
                ('errors', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'member_sync_reset_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
