"""
Django settings for healthcare_hub project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from decouple import config
from pathlib import Path
import os
SECRET_KEY = config('SECRET_KEY')

DEBUG = config('DEBUG', default=False, cast=bool)


BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-ii74!4@@vu3$j54$z%ynzh#(l^bce@ugbbv896ba^%!=j_c=il'


DEBUG = True

ALLOWED_HOSTS = ["192.168.0.135","192.168.0.239","92.168.0.135:8080","127.0.0.1:8000","127.0.0.1","localhost:8000","localhost"]

AUTH_USER_MODEL = "users.Users"


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'engine',
    'jobs',
    'users',
    'trigger',
    'reports',
    'commisions'
    

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'healthcare_hub.urls'
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://192.168.0.239:8080",
    "https://cronportal.madison.co.ke",
    "http://cronportal.madison.co.ke",  # ADD THIS
]

ALLOWED_HOSTS = [
    "192.168.0.135",
    "cronportal.madison.co.ke",
    "localhost",
    "127.0.0.1",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "x-csrftoken",
]

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS"
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'healthcare_hub.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='127.0.0.1'),
        'PORT': config('DB_PORT', default='5432'),
    },

    'external_mssql': {
        'ENGINE': 'mssql',
        'NAME': config('MSSQL_DB_NAME'),
        'USER': config('MSSQL_DB_USER'),
        'PASSWORD': config('MSSQL_DB_PASSWORD'),
        'HOST': config('MSSQL_DB_HOST'),
        'PORT': config('MSSQL_DB_PORT', default='1433'),
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'TrustServerCertificate=yes',
        },
    }
}

# DATABASES = {
    
#         'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'localdb',
#         'USER': 'smart_user',
#         'PASSWORD': 'SmartPass123!',
#         'HOST': '127.0.0.1',
#         'PORT': '5432',
    
#     },
#     # 'external_mssql': {
#     #     'ENGINE': 'mssql',
#     #     'NAME': 'healthcaredb',
#     #     'USER': 'app_user',
#     #     # 'PASSWORD': 'M@dison@!0',
#     #     'PASSWORD': 'H@1sDb_22',
#     #     'HOST': '192.168.0.160',  # IP of the SQL Server
#     #     'PORT': '1433',  
#     #     'OPTIONS': {
#     #         'driver': 'ODBC Driver 18 for SQL Server',
#     #         'extra_params': 'TrustServerCertificate=yes',
#     #     },
#     # }
#      'external_mssql': {
#         'ENGINE': 'mssql',
#         'NAME': 'healthcaredb',
#         'USER': 'app_user',
#         'PASSWORD': 'M@dison@!0',
#         'HOST': '192.168.0.110',  # IP of the SQL Server
#         'PORT': '1433',  
#         'OPTIONS': {
#             'driver': 'ODBC Driver 18 for SQL Server',
#             'extra_params': 'TrustServerCertificate=yes',
#         },
#     }
# }



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    
     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
}
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "handlers": {
#         "smart_file": {
#             "level": "INFO",
#             "class": "logging.FileHandler",
#             "filename": "logs/smart_sync.log",
#         },
#     },
#     "loggers": {
#         "smart": {
#             "handlers": ["smart_file"],
#             "level": "INFO",
#             "propagate": True,
#         },
#     },
# }





LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django settings.py

# --- Environment ---
APP_ENV = "Production"

# --- SMART API ---
SMART_CUSTOMER_ID = "MIC77FB12F4D0BA1BB7AAFC53PRODKE"
SMART_CLIENT_ID = "ad6fe9ad-d399-4ed7-a0dc-9fb53f402315"
SMART_CLIENT_SECRET = "uIFPu1waAf60MoYtQ40NGyv0Aqg"
SMART_API_BASE_URL = "https://data.smartapplicationsgroup.com/api/v2/integration/"
SMART_ACCESS_TOKEN = "https://data.smartapplicationsgroup.com/auth/integ-clients/oauth/token?"
SMART_GRANT_TYPE = "client_credentials"

HAIS_API_CONSUMER_KEY = "gZtk538L7EQ3inp2HiySC9kQlO4OTzSnyuWLHg6U"
HAIS_API_CONSUMER_SECRET = "smart2023"
HAIS_API_BASE_URL = "http://192.168.0.135:8082/hais_api/"


from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),   # 1 hour
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),   # keep default or adjust if needed
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'haisnotifications@madison.co.ke'
EMAIL_HOST_PASSWORD = 'N!271111535161oz'

# For test, send to your email
TEST_EMAIL_RECIPIENTS = ['mwangangimuvisi@gmail.com']
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# HAIS_API_BASE_URL = "http://192.168.100.164/aar/app/members/"
HAIS_CONSUMER_KEY = "mwambeyu.jnr@gmail.com"
HAIS_CONSUMER_SECRET = "smart2020"
DATA_UPLOAD_MAX_NUMBER_FIELDS = 100000

COUNTRY_CODE = "KE"
POLICY_CURRENCY_ID = "KES"
CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = "Africa/Nairobi"
