# Generated by Django 5.2.8 on 2026-02-25 09:45

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_name', models.CharField(max_length=255)),
                ('transaction_name', models.CharField(max_length=255)),
                ('request_object', models.JSONField(blank=True, null=True)),
                ('response_object', models.JSONField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Success'), (2, 'Failure')])),
                ('http_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'API Sync Log',
                'verbose_name_plural': 'API Sync Logs',
            },
        ),
        migrations.CreateModel(
            name='BenefitSyncFailure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corp_id', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('anniv', models.CharField(max_length=10)),
                ('benefit_id', models.CharField(max_length=50)),
                ('benefit_name', models.CharField(max_length=100)),
                ('policy_no', models.CharField(max_length=50)),
                ('smart_status', models.IntegerField()),
                ('smart_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BenefitSyncSuccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corp_id', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('anniv', models.CharField(max_length=10)),
                ('benefit_id', models.CharField(max_length=50)),
                ('benefit_name', models.CharField(max_length=100)),
                ('policy_no', models.CharField(max_length=50)),
                ('smart_status', models.IntegerField()),
                ('smart_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HaisCategorySyncFailure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corp_id', models.CharField(max_length=50)),
                ('category_name', models.CharField(max_length=100)),
                ('anniv', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=50)),
                ('status_code', models.IntegerField()),
                ('smart_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HaisCategorySyncSuccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corp_id', models.CharField(max_length=50)),
                ('category_name', models.CharField(max_length=100)),
                ('anniv', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=50)),
                ('status_code', models.IntegerField()),
                ('smart_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberSyncFailure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_no', models.CharField(max_length=50)),
                ('family_no', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('second_name', models.CharField(blank=True, max_length=50)),
                ('third_name', models.CharField(blank=True, max_length=50)),
                ('other_names', models.CharField(default='null', max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('anniv', models.CharField(max_length=10)),
                ('corp_id', models.CharField(max_length=50)),
                ('smart_status', models.IntegerField()),
                ('smart_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberSyncSuccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_no', models.CharField(max_length=50)),
                ('family_no', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('second_name', models.CharField(blank=True, max_length=50)),
                ('third_name', models.CharField(blank=True, max_length=50)),
                ('other_names', models.CharField(default='null', max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('anniv', models.CharField(max_length=10)),
                ('corp_id', models.CharField(max_length=50)),
                ('smart_status', models.IntegerField()),
                ('smart_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderRestrictionSyncFailure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corp_id', models.CharField(max_length=50)),
                ('provider_code', models.CharField(max_length=50)),
                ('smart_restriction_category', models.JSONField()),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status_code', models.IntegerField()),
                ('smart_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderRestrictionSyncSuccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corp_id', models.CharField(max_length=50)),
                ('provider_code', models.CharField(max_length=50)),
                ('smart_restriction_category', models.CharField(max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status_code', models.IntegerField()),
                ('smart_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('full_names', models.CharField(blank=True, max_length=150, null=True)),
                ('user_pass', models.CharField(max_length=255)),
                ('blocked', models.BooleanField(default=False)),
                ('next_login', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaitingPeriodSyncFailure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheme_id', models.CharField(max_length=50)),
                ('family_no', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('benefit', models.CharField(max_length=100)),
                ('anniv', models.CharField(max_length=50)),
                ('status_code', models.IntegerField()),
                ('smart_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaitingPeriodSyncSuccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheme_id', models.CharField(max_length=50)),
                ('family_no', models.CharField(max_length=50)),
                ('benefit', models.CharField(max_length=50)),
                ('anniv', models.CharField(max_length=50)),
                ('status_code', models.IntegerField()),
                ('smart_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
