# Generated by Django 5.2.8 on 2026-02-25 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='HAIS-SMART', max_length=50)),
                ('transaction_name', models.CharField(default='Corporate Scheme Copay', max_length=100)),
                ('status_code', models.PositiveIntegerField()),
                ('request_object', models.JSONField(blank=True, null=True)),
                ('response_object', models.JSONField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Success'), (2, 'Failure')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Copay Log',
                'verbose_name_plural': 'Copay Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='apisynclog',
            options={'verbose_name': 'schemes Api Logs', 'verbose_name_plural': 'schemes Api Logs'},
        ),
    ]
