# Generated by Django 5.2.8 on 2026-03-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_copaylog_alter_apisynclog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersyncfailure',
            name='smart_response',
            field=models.JSONField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='membersyncfailure',
            name='smart_status',
            field=models.IntegerField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='membersyncsuccess',
            name='smart_response',
            field=models.JSONField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='membersyncsuccess',
            name='smart_status',
            field=models.IntegerField(blank=True, max_length=50),
        ),
    ]
