# Generated by Django 5.2.8 on 2026-03-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_alter_membersyncfailure_smart_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersyncfailure',
            name='smart_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membersyncfailure',
            name='smart_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membersyncsuccess',
            name='smart_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membersyncsuccess',
            name='smart_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
