# Generated by Django 5.2.8 on 2026-03-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_alter_membersyncfailure_smart_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefitsyncfailure',
            name='request_object',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='benefitsyncsuccess',
            name='request_object',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='haiscategorysyncfailure',
            name='request_object',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='haiscategorysyncsuccess',
            name='request_object',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membersyncfailure',
            name='request_object',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membersyncsuccess',
            name='request_object',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerrestrictionsyncfailure',
            name='request_object',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerrestrictionsyncsuccess',
            name='request_object',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waitingperiodsyncfailure',
            name='request_object',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waitingperiodsyncsuccess',
            name='request_object',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
