# Generated by Django 5.2.8 on 2026-03-13 07:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_benefitsyncfailure_request_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopaySync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_name', models.CharField(max_length=200)),
                ('endpoint', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'FAILED'), (3, 'PENDING')], default=3)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('request_object', models.JSONField(blank=True, null=True)),
                ('response_object', models.JSONField(blank=True, null=True)),
                ('corp_id', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'copay_sync_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='copay_sync__status_1c7811_idx'), models.Index(fields=['corp_id'], name='copay_sync__corp_id_df0919_idx'), models.Index(fields=['created_at'], name='copay_sync__created_689401_idx')],
            },
        ),
    ]
