# Generated by Django 5.2.8 on 2026-04-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_copaysync'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apisynclog',
            options={'ordering': ['-created_at'], 'verbose_name': 'schemes Api Logs', 'verbose_name_plural': 'schemes Api Logs'},
        ),
    ]
