# Generated by Django 5.2.8 on 2026-04-02 16:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_alter_apisynclog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCategoryChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_no', models.CharField(max_length=50)),
                ('anniv', models.IntegerField()),
                ('request_payload', models.JSONField()),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'member_category_change_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
