# Generated by Django 5.2.8 on 2026-06-09 13:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebitCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit_credit_reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('source_pushnote_code', models.BigIntegerField(db_index=True)),
                ('transaction_code', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('client_pin', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('client_name', models.CharField(max_length=255)),
                ('transaction_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sync_status', models.CharField(db_index=True, default='PENDING', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'debit_credit_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
