# Generated by Django 5.2.8 on 2026-06-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitcredit',
            name='etims_status',
            field=models.CharField(db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='debitcredit',
            name='kra_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debitcredit',
            name='kra_ref',
            field=models.TextField(blank=True, null=True),
        ),
    ]
